services:
  traefik:
    image: traefik:3.6.4
    ports:
      - "7080:80"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './traefik.yml:/etc/traefik/traefik.yml'
      - '../.traefik.yml:/plugins-local/src/github.com/mridang/traefik-superheader/.traefik.yml'
      - '../build/plugin.wasm:/plugins-local/src/github.com/mridang/traefik-superheader/plugin.wasm'
    labels:
      - traefik.enable=true
      - traefik.http.services.traefik.loadbalancer.server.port=8080

  hello:
    image: testcontainers/helloworld
    expose:
      - "8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.hello.rule=PathPrefix(`/hello`)
      - traefik.http.routers.hello.entrypoints=web
      - traefik.http.routers.hello.middlewares=strip-hello-prefix,securehello
      - traefik.http.services.hello.loadbalancer.server.port=8080
      - traefik.http.middlewares.strip-hello-prefix.stripprefix.prefixes=/hello
      - traefik.http.middlewares.securehello.plugin.superheader.x-frame-options=DENY
      - traefik.http.middlewares.securehello.plugin.superheader.x-dns-prefetch-control=on
      - traefik.http.middlewares.securehello.plugin.superheader.x-content-type-options=on
      - traefik.http.middlewares.securehello.plugin.superheader.strict-transport-security=on
      - traefik.http.middlewares.securehello.plugin.superheader.referrer-policy=on
      - traefik.http.middlewares.securehello.plugin.superheader.x-xss-protection=on
      - traefik.http.middlewares.securehello.plugin.superheader.cross-origin-opener-policy=on
      - traefik.http.middlewares.securehello.plugin.superheader.cross-origin-embedder-policy=on
      - traefik.http.middlewares.securehello.plugin.superheader.cross-origin-resource-policy=on
      - traefik.http.middlewares.securehello.plugin.superheader.origin-agent-cluster=on
      - traefik.http.middlewares.securehello.plugin.superheader.x-permitted-cross-domain-policies=on
      - traefik.http.middlewares.securehello.plugin.superheader.remove-powered-by=on

  whoami:
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami.middlewares=securewhoami
      - traefik.http.middlewares.securewhoami.plugin.superheader.x-frame-options=sameorigin
      - traefik.http.middlewares.securewhoami.plugin.superheader.x-dns-prefetch-control=off
      - traefik.http.middlewares.securewhoami.plugin.superheader.x-content-type-options=off
      - traefik.http.middlewares.securewhoami.plugin.superheader.strict-transport-security=off
      - traefik.http.middlewares.securewhoami.plugin.superheader.referrer-policy=off
      - traefik.http.middlewares.securewhoami.plugin.superheader.x-xss-protection=off
      - traefik.http.middlewares.securewhoami.plugin.superheader.cross-origin-opener-policy=off
      - traefik.http.middlewares.securewhoami.plugin.superheader.cross-origin-embedder-policy=off
      - traefik.http.middlewares.securewhoami.plugin.superheader.cross-origin-resource-policy=off
      - traefik.http.middlewares.securewhoami.plugin.superheader.origin-agent-cluster=off
      - traefik.http.middlewares.securewhoami.plugin.superheader.x-permitted-cross-domain-policies=off
      - traefik.http.middlewares.securewhoami.plugin.superheader.remove-powered-by=off